### PR TITLE
Atlases_transformations

### PR DESCRIPTION
**Pull request by vinferrer**

### CODE REVIEW

**Comment by vinferrer** [comment]
@smoia there is a merge conflict in ``create_random_parcellation.py`` should i accept the master changes or the changes from your branch?

**Comment by smoia** [comment]
@vinferrer it's difficult for me to say without seeing it. I would go for the most recent, that should be upstream/master.

**Comment by smoia** [comment]
@vinferrer I solved the conflict!

**Comment by vinferrer** [comment]
Okay, I think is all ready

**Pull request merged**
